title: Target Tech
email: github@targetteknoloji.com
description: > # this means to ignore newlines until "baseurl:"
  Empowering Call Centers with Generative AI and Data Science Solutions
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://TargetTechGit.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Target Tech Yazılım Sanayi Ve Ticaret Limited Şirketi
address_line: Barış Mah. Koşu Yolu Cad. ARGE VE İNOVASYON Binası No 26 İç Kapı No:48 Gebze/ Kocaeli
telephone_number: +90 549 820 40 60
company_email: github@targetteknoloji.com


# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
